export { default as Functor } from 'interfaces/functor'
export { default as Apply } from 'interfaces/apply'
export { default as Applicative } from 'interfaces/applicative'
export { default as Chain } from 'interfaces/chain'
export { default as Monad } from 'interfaces/monad'
