export { default as Identity } from 'monads/identity'
export { default as Noop } from 'monads/noop'
export { default as Maybe, Just, Nothing } from 'monads/maybe'
export { default as IO } from 'monads/io'
export { default as either, Right, Left } from 'monads/either'

export { default as Functor } from 'interfaces/functor'
export { default as Apply } from 'interfaces/apply'
export { default as Applicative } from 'interfaces/applicative'
export { default as Chain } from 'interfaces/chain'
export { default as Monad } from 'interfaces/monad'
